/*
 * test_nrf_cloud_cross.c - Cross-validate PHP nRF Cloud binary against C
 *
 * Reads a binary blob generated by PHP (gen_nrf_cloud_binary.php), parses
 * the nRF Cloud schema v1 wire format, and compares every field against
 * values produced by the C conversion code in gps_assist_nrf.c.
 *
 * This ensures the PHP encoder and C encoder produce identical output
 * for the same input data.
 *
 * Usage: php tests/gen_nrf_cloud_binary.php /tmp/test.bin && \
 *        ./tests/test_nrf_cloud_cross /tmp/test.bin
 *
 * Copyright (C) 2026 Free Mobile
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <nrf_modem_gnss.h>

#include "gps_assist.h"
#include "gps_assist_nrf.h"

static int tests_run;
static int tests_passed;

#define ASSERT_TEST(cond, msg) do { \
	tests_run++; \
	if (!(cond)) { \
		fprintf(stderr, "  FAIL: %s (line %d)\n", (msg), __LINE__); \
	} else { \
		tests_passed++; \
	} \
} while (0)

#define ASSERT_EQ_INT(a, b, msg) do { \
	long long _a = (long long)(a), _b = (long long)(b); \
	tests_run++; \
	if (_a != _b) { \
		fprintf(stderr, "  FAIL: %s: %lld != %lld (line %d)\n", \
			(msg), _a, _b, __LINE__); \
	} else { \
		tests_passed++; \
	} \
} while (0)

/*
 * Mock nrf_modem functions — capture write calls.
 */
#define MAX_CAPTURES 20

static struct {
	uint8_t  buf[512];
	int32_t  len;
	uint16_t type;
} captures[MAX_CAPTURES];
static int num_captures;

int32_t nrf_modem_gnss_agnss_write(void *buf, int32_t buf_len, uint16_t type)
{
	if (num_captures < MAX_CAPTURES) {
		memcpy(captures[num_captures].buf, buf, (size_t)buf_len);
		captures[num_captures].len  = buf_len;
		captures[num_captures].type = type;
		num_captures++;
	}
	return 0;
}

int32_t nrf_modem_gnss_agnss_expiry_get(
	struct nrf_modem_gnss_agnss_expiry *expiry)
{
	(void)expiry;
	return -1;
}

/*
 * Find a capture by modem type ID.  Optional sv_id for per-SV types.
 * Returns capture index or -1.
 */
static int find_capture(uint16_t type, int sv_id)
{
	for (int i = 0; i < num_captures; i++) {
		if (captures[i].type != type)
			continue;
		if (sv_id < 0)
			return i;
		/* First byte of eph/alm structs is sv_id */
		if (captures[i].buf[0] == (uint8_t)sv_id)
			return i;
	}
	return -1;
}

/*
 * Wire format readers — little-endian, packed (no padding).
 */
static uint8_t  rd_u8(const uint8_t *p, int off) { return p[off]; }
static int8_t   rd_i8(const uint8_t *p, int off) { return (int8_t)p[off]; }

static uint16_t rd_u16(const uint8_t *p, int off)
{
	return (uint16_t)(p[off] | ((uint16_t)p[off + 1] << 8));
}

static int16_t rd_i16(const uint8_t *p, int off)
{
	return (int16_t)rd_u16(p, off);
}

static uint32_t rd_u32(const uint8_t *p, int off)
{
	return (uint32_t)p[off]
	     | ((uint32_t)p[off + 1] << 8)
	     | ((uint32_t)p[off + 2] << 16)
	     | ((uint32_t)p[off + 3] << 24);
}

static int32_t rd_i32(const uint8_t *p, int off)
{
	return (int32_t)rd_u32(p, off);
}

/*
 * nRF Cloud binary protocol type IDs (different from modem API!).
 * Cloud: TOW=6, system_clock=7, location=8
 * Modem: system_clock_and_tows=6, location=7
 */
#define CLOUD_TYPE_UTC          1
#define CLOUD_TYPE_EPHEMERIS    2
#define CLOUD_TYPE_ALMANAC      3
#define CLOUD_TYPE_KLOBUCHAR    4
#define CLOUD_TYPE_SYSTEM_CLOCK 7
#define CLOUD_TYPE_LOCATION     8
#define CLOUD_TYPE_INTEGRITY    9
#define CLOUD_TYPE_QZSS_EPH    12

/*
 * Packed wire format sizes per element (no padding).
 */
static int wire_element_size(int type_id)
{
	switch (type_id) {
	case CLOUD_TYPE_UTC:          return 14;
	case CLOUD_TYPE_EPHEMERIS:    return 62;
	case CLOUD_TYPE_ALMANAC:      return 31;
	case CLOUD_TYPE_KLOBUCHAR:    return 8;
	case 5: /* NeQuick */         return 8;
	case 6: /* TOW */             return 4;
	case CLOUD_TYPE_SYSTEM_CLOCK: return 12;
	case CLOUD_TYPE_LOCATION:     return 15;
	case CLOUD_TYPE_INTEGRITY:    return 4;
	case 11: /* QZSS almanac */   return 31;
	case CLOUD_TYPE_QZSS_EPH:    return 62;
	case 13: /* QZSS integrity */ return 4;
	default: return -1;
	}
}

/*
 * Compare PHP-encoded ephemeris (packed wire format) against C-converted
 * nrf_modem struct, field by field.
 *
 * Wire format offsets (62 bytes total):
 *   0:  sv_id(u8)    1:  health(u8)   2:  iodc(u16)    4:  toc(u16)
 *   6:  af2(i8)      7:  af1(i16)     9:  af0(i32)    13:  tgd(i8)
 *  14:  ura(u8)     15:  fit_int(u8)  16:  toe(u16)    18:  w(i32)
 *  22:  delta_n(i16)24:  m0(i32)     28:  omega_dot(i32) 32: e(u32)
 *  36:  idot(i16)   38:  sqrt_a(u32) 42:  i0(i32)     46: omega0(i32)
 *  50:  crs(i16)    52:  cis(i16)    54:  cus(i16)     56: crc(i16)
 *  58:  cic(i16)    60:  cuc(i16)
 */
static void compare_ephemeris(const uint8_t *wire, int capture_idx,
			      const char *label)
{
	const struct nrf_modem_gnss_agnss_gps_data_ephemeris *c =
		(const void *)captures[capture_idx].buf;

	char msg[128];

#define EPH_CHK(field, rd_fn, off) do { \
	snprintf(msg, sizeof(msg), "%s: %s", label, #field); \
	ASSERT_EQ_INT(rd_fn(wire, off), c->field, msg); \
} while (0)

	EPH_CHK(sv_id,     rd_u8,  0);
	EPH_CHK(health,    rd_u8,  1);
	EPH_CHK(iodc,      rd_u16, 2);
	EPH_CHK(toc,       rd_u16, 4);
	EPH_CHK(af2,       rd_i8,  6);
	EPH_CHK(af1,       rd_i16, 7);
	EPH_CHK(af0,       rd_i32, 9);
	EPH_CHK(tgd,       rd_i8,  13);
	EPH_CHK(ura,       rd_u8,  14);
	EPH_CHK(fit_int,   rd_u8,  15);
	EPH_CHK(toe,       rd_u16, 16);
	EPH_CHK(w,         rd_i32, 18);
	EPH_CHK(delta_n,   rd_i16, 22);
	EPH_CHK(m0,        rd_i32, 24);
	EPH_CHK(omega_dot, rd_i32, 28);
	EPH_CHK(e,         rd_u32, 32);
	EPH_CHK(idot,      rd_i16, 36);
	EPH_CHK(sqrt_a,    rd_u32, 38);
	EPH_CHK(i0,        rd_i32, 42);
	EPH_CHK(omega0,    rd_i32, 46);
	EPH_CHK(crs,       rd_i16, 50);
	EPH_CHK(cis,       rd_i16, 52);
	EPH_CHK(cus,       rd_i16, 54);
	EPH_CHK(crc,       rd_i16, 56);
	EPH_CHK(cic,       rd_i16, 58);
	EPH_CHK(cuc,       rd_i16, 60);

#undef EPH_CHK
}

/*
 * Compare PHP-encoded almanac (packed wire format) against C-converted
 * nrf_modem struct, field by field.
 *
 * Wire format offsets (31 bytes total):
 *   0:  sv_id(u8)    1:  wn(u8)      2:  toa(u8)      3:  ioda(u8)
 *   4:  e(u16)       6:  delta_i(i16) 8: omega_dot(i16) 10: sv_health(u8)
 *  11:  sqrt_a(u32) 15:  omega0(i32) 19:  w(i32)      23:  m0(i32)
 *  27:  af0(i16)    29:  af1(i16)
 */
static void compare_almanac(const uint8_t *wire, int capture_idx,
			    const char *label)
{
	const struct nrf_modem_gnss_agnss_gps_data_almanac *c =
		(const void *)captures[capture_idx].buf;

	char msg[128];

#define ALM_CHK(field, rd_fn, off) do { \
	snprintf(msg, sizeof(msg), "%s: %s", label, #field); \
	ASSERT_EQ_INT(rd_fn(wire, off), c->field, msg); \
} while (0)

	ALM_CHK(sv_id,     rd_u8,  0);
	ALM_CHK(wn,        rd_u8,  1);
	ALM_CHK(toa,       rd_u8,  2);
	ALM_CHK(ioda,      rd_u8,  3);
	ALM_CHK(e,         rd_u16, 4);
	ALM_CHK(delta_i,   rd_i16, 6);
	ALM_CHK(omega_dot, rd_i16, 8);
	ALM_CHK(sv_health, rd_u8,  10);
	ALM_CHK(sqrt_a,    rd_u32, 11);
	ALM_CHK(omega0,    rd_i32, 15);
	ALM_CHK(w,         rd_i32, 19);
	ALM_CHK(m0,        rd_i32, 23);
	ALM_CHK(af0,       rd_i16, 27);
	ALM_CHK(af1,       rd_i16, 29);

#undef ALM_CHK
}

/*
 * Compare Klobuchar (8 bytes): alpha0..3, beta0..3 (all int8).
 */
static void compare_klobuchar(const uint8_t *wire, int capture_idx)
{
	const struct nrf_modem_gnss_agnss_data_klobuchar *c =
		(const void *)captures[capture_idx].buf;

	ASSERT_EQ_INT(rd_i8(wire, 0), c->alpha0, "klob: alpha0");
	ASSERT_EQ_INT(rd_i8(wire, 1), c->alpha1, "klob: alpha1");
	ASSERT_EQ_INT(rd_i8(wire, 2), c->alpha2, "klob: alpha2");
	ASSERT_EQ_INT(rd_i8(wire, 3), c->alpha3, "klob: alpha3");
	ASSERT_EQ_INT(rd_i8(wire, 4), c->beta0,  "klob: beta0");
	ASSERT_EQ_INT(rd_i8(wire, 5), c->beta1,  "klob: beta1");
	ASSERT_EQ_INT(rd_i8(wire, 6), c->beta2,  "klob: beta2");
	ASSERT_EQ_INT(rd_i8(wire, 7), c->beta3,  "klob: beta3");
}

/*
 * Compare UTC (14 bytes): a1(i32) a0(i32) tot(u8) wn_t(u8)
 *                          delta_tls(i8) wn_lsf(u8) dn(i8) delta_tlsf(i8)
 */
static void compare_utc(const uint8_t *wire, int capture_idx)
{
	const struct nrf_modem_gnss_agnss_gps_data_utc *c =
		(const void *)captures[capture_idx].buf;

	ASSERT_EQ_INT(rd_i32(wire, 0), c->a1,        "utc: a1");
	ASSERT_EQ_INT(rd_i32(wire, 4), c->a0,        "utc: a0");
	ASSERT_EQ_INT(rd_u8(wire,  8), c->tot,       "utc: tot");
	ASSERT_EQ_INT(rd_u8(wire,  9), c->wn_t,      "utc: wn_t");
	ASSERT_EQ_INT(rd_i8(wire, 10), c->delta_tls, "utc: delta_tls");
	/*
	 * wn_lsf, dn, delta_tlsf: PHP sets wn_lsf=wn_t, dn=0,
	 * delta_tlsf=dt_ls since the RINEX data doesn't carry future
	 * leap-second info.  The C inject_utc() leaves these as 0
	 * (from memset).  So we don't compare these 3 fields — they
	 * are not in the RINEX source data.
	 */
}

/*
 * Compare system time (12 bytes): date_day(u16) time_full_s(u32)
 *                                  time_frac_ms(u16) sv_mask(u32)
 */
static void compare_system_time(const uint8_t *wire, int capture_idx)
{
	const struct nrf_modem_gnss_agnss_gps_data_system_time_and_sv_tow *c =
		(const void *)captures[capture_idx].buf;

	ASSERT_EQ_INT(rd_u16(wire, 0), c->date_day,     "stime: date_day");
	ASSERT_EQ_INT(rd_u32(wire, 2), c->time_full_s,  "stime: time_full_s");
	ASSERT_EQ_INT(rd_u16(wire, 6), c->time_frac_ms, "stime: time_frac_ms");
	ASSERT_EQ_INT(rd_u32(wire, 8), c->sv_mask,      "stime: sv_mask");
}

/*
 * Compare location (15 bytes): lat(i32) lon(i32) alt(i16) unc_smj(u8)
 *                               unc_smn(u8) orient(u8) unc_alt(u8) conf(u8)
 *
 * PHP uses floor() for lat/lon, C uses round() — allow ±1 tolerance.
 */
static void compare_location(const uint8_t *wire, int capture_idx)
{
	const struct nrf_modem_gnss_agnss_data_location *c =
		(const void *)captures[capture_idx].buf;

	int32_t php_lat = rd_i32(wire, 0);
	int32_t php_lon = rd_i32(wire, 4);
	char msg[128];

	snprintf(msg, sizeof(msg), "loc: lat %d vs %d (±1)",
		 php_lat, c->latitude);
	ASSERT_TEST(abs(php_lat - c->latitude) <= 1, msg);

	snprintf(msg, sizeof(msg), "loc: lon %d vs %d (±1)",
		 php_lon, c->longitude);
	ASSERT_TEST(abs(php_lon - c->longitude) <= 1, msg);

	ASSERT_EQ_INT(rd_i16(wire, 8), c->altitude,  "loc: altitude");
	/* Uncertainty: PHP uses max (127), C uses K=18 — different by design */
}

/*
 * Set up test data matching the PHP gen_nrf_cloud_binary.php script.
 */
static void setup_test_data(struct gps_assist_data *data)
{
	memset(data, 0, sizeof(*data));

	data->timestamp = 1773064800;
	data->gps_week  = 2409;

	/* GPS PRN 1 */
	data->num_sv = 1;
	struct gps_ephemeris *sv = &data->sv[0];
	sv->prn       = 1;
	sv->health    = 0;
	sv->iodc      = 933;
	sv->iode      = 165;
	sv->week      = 2409;
	sv->toe       = 396000;
	sv->toc       = 396000;
	sv->af0       = -2.578310668468e-05;
	sv->af1       = -2.842170943040e-14;
	sv->af2       = 0.0;
	sv->sqrt_a    = 5153.648925781250;
	sv->e         = 5.483717424795e-03;
	sv->i0        = 9.755508981940e-01;
	sv->omega0    = -2.025233279608;
	sv->omega     = -1.722784098283;
	sv->m0        = 1.296410068666;
	sv->delta_n   = 4.200289988741e-09;
	sv->omega_dot = -7.793218395069e-09;
	sv->idot      = -2.078767516450e-10;
	sv->cuc       = -2.935528755188e-06;
	sv->cus       = 8.162856101990e-06;
	sv->crc       = 222.65625;
	sv->crs       = -48.0625;
	sv->cic       = 1.043081283569e-07;
	sv->cis       = 1.303851604462e-07;
	sv->tgd       = -1.117587089539e-08;

	/* QZSS PRN 193 */
	data->num_qzss = 1;
	struct gps_ephemeris *qzss = &data->qzss[0];
	qzss->prn       = 193;
	qzss->health    = 0;
	qzss->iodc      = 10;
	qzss->iode      = 10;
	qzss->week      = 2409;
	qzss->toe       = 396000;
	qzss->toc       = 396000;
	qzss->af0       = -1.0e-06;
	qzss->af1       = 0.0;
	qzss->af2       = 0.0;
	qzss->sqrt_a    = 6493.296875;
	qzss->e         = 0.075;
	qzss->i0        = 0.7330382858;
	qzss->omega0    = 2.356194490;
	qzss->omega     = -1.570796327;
	qzss->m0        = 0.785398163;
	qzss->delta_n   = 3.0e-09;
	qzss->omega_dot = -6.0e-09;
	qzss->idot      = 1.0e-10;

	/* Almanac PRN 1 (angles in semi-circles) */
	data->num_alm = 1;
	struct gps_almanac *alm = &data->alm[0];
	alm->prn       = 1;
	alm->health    = 0;
	alm->ioda      = 2;
	alm->week      = 2409;
	alm->toa       = 405504;
	alm->e         = 5.48e-03;
	alm->delta_i   = -1.54e-03;
	alm->omega_dot = -2.48e-09;
	alm->sqrt_a    = 5153.65;
	alm->omega0    = -0.644;
	alm->omega     = -0.548;
	alm->m0        = 0.412;
	alm->af0       = -2.58e-05;
	alm->af1       = -2.84e-14;

	/* Ionosphere */
	data->iono.alpha[0] = 1.118e-08;
	data->iono.alpha[1] = 0.0;
	data->iono.alpha[2] = -5.961e-08;
	data->iono.alpha[3] = 0.0;
	data->iono.beta[0]  = 9.011e+04;
	data->iono.beta[1]  = 0.0;
	data->iono.beta[2]  = -1.966e+05;
	data->iono.beta[3]  = 0.0;

	/* UTC */
	data->utc.a0    = 1.863e-09;
	data->utc.a1    = 4.441e-15;
	data->utc.tot   = 233472;
	data->utc.wnt   = 2409;
	data->utc.dt_ls = 18;

	/* Location */
	data->location.latitude  = 48.853;
	data->location.longitude = 2.3498;
	data->location.altitude  = 35;
	data->location.valid     = 1;
}

/*
 * Run C conversions via gps_assist_inject_*() public API.
 * The mock nrf_modem_gnss_agnss_write() captures each struct.
 */
static void run_c_conversions(const struct gps_assist_data *data)
{
	num_captures = 0;

	/* GPS ephemeris PRN 1 */
	gps_assist_inject_ephemeris(data, 1);

	/* GPS almanac PRN 1 (will use parsed almanac) */
	gps_assist_inject_almanac(data, 1);

	/* QZSS ephemeris PRN 193 */
	gps_assist_inject_qzss_ephemeris(data, 193);

	/* Klobuchar */
	gps_assist_inject_klobuchar(data);

	/* UTC */
	gps_assist_inject_utc(data);

	/* System time */
	gps_assist_inject_system_time(data);

	/* Location */
	gps_assist_inject_location(data);
}

int main(int argc, char *argv[])
{
	if (argc < 2) {
		fprintf(stderr, "Usage: %s <binary_file>\n", argv[0]);
		return 1;
	}

	printf("=== test_nrf_cloud_cross: PHP vs C cross-validation ===\n");

	/* Step 1: Run C conversions to produce reference structs */
	struct gps_assist_data data;

	setup_test_data(&data);
	run_c_conversions(&data);

	printf("  C conversions: %d captures\n", num_captures);
	ASSERT_TEST(num_captures == 7, "expected 7 captures");

	/* Step 2: Read PHP binary file */
	FILE *f = fopen(argv[1], "rb");
	if (!f) {
		fprintf(stderr, "Cannot open %s\n", argv[1]);
		return 1;
	}

	fseek(f, 0, SEEK_END);
	long file_size = ftell(f);
	fseek(f, 0, SEEK_SET);

	uint8_t *blob = malloc((size_t)file_size);
	if (!blob || fread(blob, 1, (size_t)file_size, f) != (size_t)file_size) {
		fprintf(stderr, "Failed to read %s\n", argv[1]);
		return 1;
	}
	fclose(f);

	printf("  PHP binary: %ld bytes\n", file_size);

	/* Step 3: Verify schema version */
	ASSERT_EQ_INT(blob[0], 1, "schema version");

	/* Step 4: Walk element groups and compare */
	int pos = 1;
	int groups_found = 0;

	while (pos < file_size) {
		int type_id = blob[pos];
		int count   = rd_u16(blob, pos + 1);
		int elem_sz = wire_element_size(type_id);
		pos += 3;

		if (elem_sz < 0) {
			fprintf(stderr, "  Unknown type %d at offset %d\n",
				type_id, pos - 3);
			break;
		}

		printf("  type=%d count=%d elem_size=%d\n",
			type_id, count, elem_sz);

		for (int i = 0; i < count; i++) {
			const uint8_t *elem = blob + pos;
			int ci;

			switch (type_id) {
			case CLOUD_TYPE_EPHEMERIS:
				/* Map to modem type 2, find by sv_id */
				ci = find_capture(
					NRF_MODEM_GNSS_AGNSS_GPS_EPHEMERIDES,
					elem[0]);
				if (ci >= 0)
					compare_ephemeris(elem, ci,
							  "GPS eph");
				else
					ASSERT_TEST(0, "GPS eph: no C capture");
				break;

			case CLOUD_TYPE_QZSS_EPH:
				/* QZSS uses same modem type 2 */
				ci = find_capture(
					NRF_MODEM_GNSS_AGNSS_GPS_EPHEMERIDES,
					elem[0]);
				if (ci >= 0)
					compare_ephemeris(elem, ci,
							  "QZSS eph");
				else
					ASSERT_TEST(0, "QZSS eph: no C capture");
				break;

			case CLOUD_TYPE_ALMANAC:
				ci = find_capture(
					NRF_MODEM_GNSS_AGNSS_GPS_ALMANAC,
					elem[0]);
				if (ci >= 0)
					compare_almanac(elem, ci,
							"GPS alm");
				else
					ASSERT_TEST(0, "GPS alm: no C capture");
				break;

			case CLOUD_TYPE_KLOBUCHAR:
				ci = find_capture(
					NRF_MODEM_GNSS_AGNSS_KLOBUCHAR_IONOSPHERIC_CORRECTION,
					-1);
				if (ci >= 0)
					compare_klobuchar(elem, ci);
				else
					ASSERT_TEST(0, "klob: no C capture");
				break;

			case CLOUD_TYPE_UTC:
				ci = find_capture(
					NRF_MODEM_GNSS_AGNSS_GPS_UTC_PARAMETERS,
					-1);
				if (ci >= 0)
					compare_utc(elem, ci);
				else
					ASSERT_TEST(0, "utc: no C capture");
				break;

			case CLOUD_TYPE_SYSTEM_CLOCK:
				ci = find_capture(
					NRF_MODEM_GNSS_AGNSS_GPS_SYSTEM_CLOCK_AND_TOWS,
					-1);
				if (ci >= 0)
					compare_system_time(elem, ci);
				else
					ASSERT_TEST(0, "stime: no C capture");
				break;

			case CLOUD_TYPE_LOCATION:
				ci = find_capture(
					NRF_MODEM_GNSS_AGNSS_LOCATION,
					-1);
				if (ci >= 0)
					compare_location(elem, ci);
				else
					ASSERT_TEST(0, "loc: no C capture");
				break;

			case CLOUD_TYPE_INTEGRITY:
				ASSERT_EQ_INT(rd_u32(elem, 0),
					      0xFFFFFFFF,
					      "integrity: all healthy");
				break;
			}

			pos += elem_sz;
		}

		groups_found++;
	}

	ASSERT_EQ_INT(pos, file_size, "fully consumed");
	ASSERT_TEST(groups_found >= 7, "at least 7 element groups");

	free(blob);

	printf("\ntest_nrf_cloud_cross: %d/%d passed\n",
		tests_passed, tests_run);
	return tests_passed < tests_run ? 1 : 0;
}
